[settings]
experimental = true # So hooks are run.
lockfile = true

[tools]
pdm = "latest"
python = "3.14"
opencode = "latest"
pre-commit = "latest"
shellcheck = "latest"

[hooks]
postinstall = [
    "pre-commit install --hook-type pre-commit --hook-type pre-push",
    "pdm config lock.format pylock",
    "pdm install --plugins",
    "pdm install"
]

[env]
_.python.venv = { path = ".venv", create = true }

[tasks.test]
description = "Run test suite"
run = "pytest"

[tasks.fmt]
description = "Format code"
run = "ruff format"

[tasks.lint]
description = "Lint and auto-fix"
run = "ruff check --fix"

[tasks.typecheck]
description = "Run static type checks"
run = "mypy src"

[tasks.audit]
description = "Check dependencies for vulnerabilities"
run = "pip-audit"

[tasks.shellcheck]
description = "Lint shell scripts"
run = "git grep -lz '^#!.*\\b\\(bash\\|sh\\)\\b' -- | xargs -0 -r shellcheck"

[tasks.run]
description = "Run app with a Yoto URL"
run = "pdm run toto_backup {{arg(name='url')}}"

[tasks.build]
description = "Build package artifacts"
run = "pdm build"

[tasks.pyz]
description = "Build zipapp"
run = "shiv --output-file toto-backup.pyz --console-script toto_backup ."

[tasks.check]
description = "Run formatter, linter, typechecker, and tests"
depends = ["fmt", "lint", "typecheck", "shellcheck", "test"]
