[settings]
experimental = true # So hooks are run.
lockfile = true

[tools]
opencode = "latest"
python = "3.14"
pipx = "latest"
pdm = "latest"
pre-commit = { version = "latest", postinstall = "pre-commit install --install-hooks --hook-type pre-commit --hook-type pre-push" }
shellcheck = "latest"
actionlint = "latest"
gh = "latest"

[hooks]
postinstall = [
    "pdm config lock.format pylock",
    "pdm install --plugins",
    "pdm install",
]

[env]
_.python.venv = { path = ".venv", create = true }

[tasks.test]
description = "Run test suite."
run = "pytest"

[tasks.ruff-format]
description = "Run ruff format."
hide = true
run = "ruff format"

[tasks.ruff-check]
description = "Run ruff check."
hide = true
run = "ruff check --fix --exit-non-zero-on-fix"

[tasks.mypy]
description = "Run mypy."
hide = true
run = "mypy src"

[tasks.shellcheck]
description = "Run shellcheck."
hide = true
run = "git grep -lz '^#!.*\\b\\(bash\\|sh\\)\\b' -- | xargs -0 -r shellcheck"

[tasks.actionlint]
description = "Run actionlint."
hide = true
run = "actionlint"

[tasks.audit]
description = "Check dependencies for vulnerabilities."
run = "pip-audit"

[tasks.run-app]
description = "Run app with a Yoto URL."
usage = '''
arg "<url>"
'''
run = 'pdm run toto_backup "${usage_url}"'

[tasks.build]
description = "Build package artifacts."
run = "pdm build"

[tasks.pyz]
description = "Build zipapp"
run = "shiv --output-file toto-backup.pyz --console-script toto_backup ."

[tasks.check]
description = "Run formatter, linter, typechecker, and tests"
depends = ["actionlint", "ruff-format", "ruff-check", "mypy", "shellcheck", "test"]
