#!/usr/bin/env bash
set -euo pipefail

#MISE description="Validate and fix license headers in Python sources"

AUTHOR=$(uv run tomlq .project.authors[0].name pyproject.toml)
PROJECT=$(uv run tomlq .project.name pyproject.toml)
REPO=$(uv run tomlq .project.urls.repository pyproject.toml)

uv run licenseheaders --dir src --current-year --owner "$AUTHOR" --projname "$PROJECT" --projurl "$REPO" --tmpl ./.licenseheader.j2 --ext .py
uv run licenseheaders --dir tests --current-year --owner "$AUTHOR" --projname "$PROJECT" --projurl "$REPO" --tmpl ./.licenseheader.j2 --ext .py
