name: Build

on:
  push:
    branches: [ "**" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PDM_LOCKFILE: pylock.toml

jobs:
  Check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: 3.14

      - name: Install PDM
        run: python -m pip install "pdm==2.26.7"

      - name: Install dependencies
        run: |
          pdm sync -G dev

      - name: Install pre-commit
        run: python -m pip install pre-commit

      - name: ShellCheck
        run: pre-commit run shellcheck --all-files

      - name: License headers
        run: |
          pdm run bash ./.mise/tasks/licenseheaders
          git diff --exit-code -- src tests

      - name: Ruff format
        run: pdm run ruff format --check src tests

      - name: Ruff check
        run: pdm run ruff check --no-fix src tests

      - name: Mypy
        run: pdm run mypy src

      - name: Pip audit
        run: pdm run pip-audit

  Test:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10", "3.11", "3.12", "3.13", "3.14" ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install PDM
        run: python -m pip install "pdm==2.26.7"

      - name: Install dependencies
        run: |
          pdm sync -G dev

      - name: Run tests
        run: pdm run pytest

  Build:
    needs:
      - Check
      - Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: 3.14

      - name: Install PDM
        run: python -m pip install "pdm==2.26.7"

      - name: Install dependencies
        run: |
          pdm sync -G dev

      - name: Build
        run: |
          pdm run shiv --output-file toto-backup.pyz --console-script toto_backup .

      - name: Upload build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: dist-artifacts
          path: "*.pyz"
