name: Build

on:
  push:
    branches: [ "**" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v7

      - name: Setup mise
        uses: jdx/mise-action@v4
        with:
          cache_key_prefix: mise-v1

      - name: ShellCheck
        run: mise run shellcheck

      - name: License headers
        run: |
          mise run licenseheaders
          git diff --exit-code -- src tests

      - name: Ruff format
        run: mise run ruff-format -- --check

      - name: Ruff check
        run: mise run ruff-check

      - name: Mypy
        run: mise run mypy

      - name: Pip audit
        run: mise run audit

  Test:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10", "3.11", "3.12", "3.13", "3.14" ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v7

      - name: Setup mise
        uses: jdx/mise-action@v4
        with:
          cache_key_prefix: mise-v1

      - name: Run tests
        run: mise exec python@${{ matrix.python-version }} -- uv run pytest

  Build:
    needs:
      - Check
      - Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v7

      - name: Setup mise
        uses: jdx/mise-action@v4
        with:
          cache_key_prefix: mise-v1

      - name: Build
        run: |
          mise run pyz

      - name: Upload build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: dist-artifacts
          path: "*.pyz"
