name: Run Checks

on:
  push:
    tags: [ "*" ]
    branches: [ "master" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - uses: pdm-project/setup-pdm@v4
        with:
          python-version: 3.13
          cache: true

      - name: Install dependencies
        run: |
          pdm venv create --force
          pdm install -G dev

      - name: Ruff format
        run: pdm run ruff format --check src tests

      - name: Ruff check
        run: pdm run ruff check --no-fix src tests

      - name: Mypy
        run: pdm run mypy src

      - name: Pip audit
        run: pdm run pip-audit
