name: Release

on:
  push:
    tags:
      - 'v*'  # Trigger on tags starting with 'v'

jobs:
  Release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - uses: pdm-project/setup-pdm@v4
        with:
          python-version: 3.13
          cache: true

      - name: Install dependencies
        run: |
          pdm install -G dev

      - name: Build
        run: |
          pdm build

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.tar.gz
            dist/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
