name: Release

on:
  push:
    tags:
      - 'v*'  # Trigger on tags starting with 'v'

env:
  PDM_LOCKFILE: pylock.toml

jobs:
  Release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v5
        with:
          python-version: 3.14

      - name: Install PDM
        run: python -m pip install "pdm==2.26.7"

      - name: Install dependencies
        run: |
          pdm sync -G dev --frozen-lockfile

      - name: Build
        run: |
          pdm run shiv --output-file toto-backup.pyz --console-script toto_backup .

      - name: Create draft release
        uses: softprops/action-gh-release@v3
        if: github.ref_type == 'tag'
        with:
          files: |
            *.pyz
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
