name: Release

on:
  push:
    tags:
      - 'v*'  # Trigger on tags starting with 'v'

jobs:
  Release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v5

      - uses: pdm-project/setup-pdm@v4
        with:
          python-version: 3.13
          cache: true

      - name: Install dependencies
        run: |
          pdm install -G dev

      - name: Build
        run: |
          pdm run shiv --output-file toto-backup.pyz --console-script toto_backup .

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.pyz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
