name: Run Tests

on:
  workflow_run:
    workflows: [ "Run Checks" ]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10", 3.11, 3.12, 3.13 ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: false

      - name: Install dependencies
        run: |
          pdm venv create --force
          pdm install -G dev

      - name: Run tests
        run: pdm run pytest
