name: Tests

on:
  workflow_dispatch:
  pull_request:
  push:
    tags: [ "*" ]
    branches: [ "master" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Test:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10", 3.11, 3.12, 3.13 ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - uses: pdm-project/setup-pdm@v4

      - name: Install dependencies
        run: |
          pdm install --plugins
          pdm install

      - name: Run tests
        run: pytest
